### ISSUE TITLE
How to install it with Spacemacs?

### ISSUE THREAD

**Issue by pshevtsov** [leafOfTree/svelte-mode#1]
I'm new to Emacs and I use Spacemacs configuration. Could you please provide me with some hints how to install svelte-mode with Spacemacs. Thanks!

**Comment by leafOfTree** [comment]
You're welcome.  Spacemacs configuration file is `~/.spacemacs` which is auto-generated. You can clone this plugin, then add two lines inside  the function `dotspacemacs/user-config`.
First
```
git clone https://github.com/leafOfTree/svelte-mode --depth 1
```
Then edit file`~/.spacemacs`
```lisp
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."

  ; Add here
  (add-to-list 'load-path "/path/to/svelte-mode")
  (require 'svelte-mode)
```

Restart emacs and open any `.svelte` file,  it should be auto-enabled if everything goes well.

**Comment by pshevtsov** [comment]
Works awesome, thanks!
