### ISSUE TITLE
Support script lang="ts"

### ISSUE THREAD

**Issue by orge-dev** [leafOfTree/svelte-mode#14]
There is no syntax highlighting (maybe other features missing too) inside a `<script lang="ts">` block.

**Comment by leafOfTree** [comment]
hi, thanks for the feedback. 

Does Emacs have syntax highlight on a normal typescript file?
It requires `typescript-mode` to highlight `<script lang="ts">` block

**Comment by apoorv569** [comment]
I am having the same issue,
![2024-08-07_22-38_1](https://github.com/user-attachments/assets/321037a7-a9bd-41c9-b603-84138cd4131c)
there is no syntax highlight in `<script lang="ts">` block.

I have `typescript-mode` installed and `typescript` files has correct syntax highlighting,
![2024-08-07_22-38](https://github.com/user-attachments/assets/85c0cfaf-6c31-4ad9-983b-44ad30fee42d)

I don't have syntax highlighting in `<style>` tag either,
![2024-08-07_22-42](https://github.com/user-attachments/assets/f7bd0443-2ab8-4f14-8e34-587502ec5bf4)

and regular `css` files show up correctly,
![2024-08-07_22-45](https://github.com/user-attachments/assets/4139d3fb-fe15-4418-89a0-1f1c77370efa)

the `html` syntax highlight is there but not quite as it appears in `html-mode`
![2024-08-07_22-50](https://github.com/user-attachments/assets/30d7d2e7-d200-4864-ab7b-f3f50ae09b34)

a regular `html` file looks like this,
![2024-08-07_22-49](https://github.com/user-attachments/assets/9505f333-530a-4a99-9511-8e1f69e30cc1)

**Comment by leafOfTree** [comment]
Thanks. I tried the latest version which does have the issue. Will look into it.

**Comment by apoorv569** [comment]
> Thanks. I tried the latest version (I compiled 31.0.50) which does have the issue.

I am using `emacs-next` package on GNU Guix, which is version,
```
  emacs --version
GNU Emacs 30.0.60
```

> My issue is fixed by installing `typescript-mode`.

I have `typescript-mode` installed already, but still having this issue.

> Are you using pre-built version `29.4`? Will check on that.

Are you talking about `emacs` version? My `emacs` version ATM is `30.0.60`.

**Comment by orge-dev** [comment]
> Does Emacs have syntax highlight on a normal typescript file? It requires `typescript-mode` to highlight `<script lang="ts">` block

Ah, totally missed that 🫣, maybe because I was using `typescript-ts-mode` in other files. It does work after I install `typescript-mode` and I'm on version 29.4. Thanks!

**Comment by leafOfTree** [comment]
Thanks for your feedback. I'll test the `emacs-next` package on GNU Guix.

**Comment by leafOfTree** [comment]
I tested with `svelte-mode`, `typescript-mode`, `eglot`, and `svelteserver`.

Mine looks like this. It doesn't highlight these symbols like yours`{}`, `[]`, `()`.... Do you use any other package for highlight?

<img width="313" alt="image" src="https://github.com/user-attachments/assets/1c52dd8e-756f-4e8e-a39f-15a4f38158f5">

**Comment by apoorv569** [comment]
@leafOfTree

> Do you use any other package for highlight?

Hmm.. Not sure, I tried disabling `flycheck` and `flymake` but those didn't do anything, what other minor mode could be doing this. I don't use that many modes for highlighting or something. As `lsp`/`eglot` does most of the work.

What would you suggest looking out for?

**Comment by leafOfTree** [comment]
You can first only enable svelte-mode to see if the issue still exists. Then enable some modes step-by-step to troubleshoot potential issues.
