### ISSUE TITLE
Change indentation offset

### ISSUE THREAD

**Issue by Tiv0w** [leafOfTree/svelte-mode#3]
Is there a variable to customize so I can change the indentation offset?
By default I just indented the code and it gave me this:
```svelte
<script>
  let name = '';
  let nameRegex = /[a-zA-Z]{2,20}/;

  function verify() {
      return name.match(nameRegex);
  }
...
```

The first indent level is 2 (which is what I want), but the second level (in the function) is 4.
How can I change this?

**Comment by leafOfTree** [comment]
Thank you for the feedback. I revised the indentation which I thought solely depended on one variable. 
As you could find in https://github.com/leafOfTree/svelte-mode#customize, now there is a new variable `svelte-basic-offset` to handle the indentation offset of the whole file.

**Comment by leafOfTree** [comment]
I'm closing this issue. Feel free to reopen it if there is any problem.
