### ISSUE TITLE
Enable autocompletion in svelte files in spacemacs

### ISSUE THREAD

**Issue by ImmanuelSamuel** [leafOfTree/svelte-mode#6]
Is there a way to enable auto-completion in svelte files kind of like in vue files where auto-completion works for js, html and css.

I have auto-complete layer initialized in the .spacemacs file.

**Comment by leafOfTree** [comment]
Thanks. That's a good idea. I'll figure out how to enable auto-completion in svelte files in spacemacs.

**Comment by leafOfTree** [comment]
Hi, I tried <kbd>m-x</kbd> `company-mode` and it appeared to work for JavaScript, HTML and CSS in svelte files. 
Then I restarted emacs. Unfortunately, something accidentally went wrong. The `company-mode` was missing and all packages installed after that complained `wrong type argument: stringp, <package-name>`. I'm still working on it. Do you know what happened?

**Comment by leafOfTree** [comment]
Hi, it has been a little long. I've added auto-completion (company-mode) support in spacemacs based on the Vue layer https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bframeworks/vue/funcs.el. After the update and opening any `.svelte` file, it will auto-enable `company-mode` for script, style and template.

**Comment by leafOfTree** [comment]
I'm closing it. Feel free to reopen it if any questions.
