### ISSUE TITLE
The code should not assume it's running on spacemacs

### ISSUE THREAD

**Issue by ineu** [leafOfTree/svelte-mode#7]
I'm using svelte-mode with doom-emacs. After a recent upgrade I'm encountering an issue cause by https://github.com/leafOfTree/svelte-mode/blob/f9fda07bc4d697b8121d73ca5e6893a4d0fa4fee/svelte-mode.el#L732 (I don't have company completely set up). 

The code should not assume it's running in a specific distribution in emacs. It can be used in a vanilla emacs as well.

**Comment by leafOfTree** [comment]
I've tried it with doom-emacs and it looks good. I'm closing it. Feel free to reopen it if any questions.

![image](https://user-images.githubusercontent.com/13349592/117152097-47989080-adec-11eb-8ec5-e979d5220f58.png)
